name: DiscordWhitelist
version: '1.0-SNAPSHOT'
main: de.steallight.discordwhitelist.DiscordWhitelist
author: "SteallightDEV"
api-version: '1.20'
commands:
  wl:
    description: "Verwalte die Whitelist auf dem Server"