name: DiscordWhitelisting Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref_name, 'stable')
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build JAR
        run: mvn clean package

      - name: Create Release
        id: create_release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: DiscordWhitelisting ${{ github.ref_name }}
          body: "Automatischer Stable-Release."
          draft: false
          prerelease: false

      - name: Upload JAR as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/*.jar
          asset_name: DiscordWhitelisting-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive